# Generated by Django 3.2 on 2023-01-25 21:43

from django.db import migrations, models
import utils.generate_code


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230126_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.CharField(default=utils.generate_code.generate_code, max_length=10, verbose_name='Code'),
        ),
    ]
