# Generated by Django 3.2 on 2023-01-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Citiess'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Contries'},
        ),
    ]
