# Generated by Django 4.1.5 on 2023-02-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0003_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="about",
            field=models.CharField(max_length=300, verbose_name="About"),
        ),
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.CharField(max_length=100, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(max_length=30, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="company",
            name="fb_link",
            field=models.URLField(blank=True, null=True, verbose_name="Fb_Link"),
        ),
        migrations.AlterField(
            model_name="company",
            name="ins_link",
            field=models.URLField(blank=True, null=True, verbose_name="Ins_link"),
        ),
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(upload_to="company/", verbose_name="Logo"),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone_number",
            field=models.CharField(max_length=20, verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="company",
            name="tw_link",
            field=models.URLField(blank=True, null=True, verbose_name="Tw_link"),
        ),
    ]
