# Generated by Django 4.1.5 on 2023-02-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="active",
            field=models.BooleanField(default=False, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(upload_to="banner/", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="banner",
            name="subtitle",
            field=models.CharField(max_length=400, verbose_name="Subtitle"),
        ),
        migrations.AlterField(
            model_name="banner",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Title"),
        ),
    ]
