# Generated by Django 4.1.5 on 2023-01-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_brand_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="", upload_to="Product/"),
            preserve_default=False,
        ),
    ]
