# Generated by Django 4.1.5 on 2023-02-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
